/**
 * 서비스별 헬스 체크 정의
 */

import type { HealthCheckDefinition } from './healthCheckTypes.js';

export const GS25_CLOUDFRONT_403_PATTERNS = [
  '403 Forbidden',
  'The request could not be satisfied',
  '403 ERROR',
];

export const EMART24_UPSTREAM_403_PATTERNS = [
  '403 Forbidden',
  '<title>403 Forbidden</title>',
];

export const SEVENELEVEN_UPSTREAM_403_PATTERNS = [
  '403 Forbidden',
  '_Incapsula_Resource',
  'NOINDEX, NOFOLLOW',
];

export const HEALTH_CHECKS: HealthCheckDefinition[] = [
  {
    id: 'cli.contract',
    service: 'cli',
    target: 'api-contract',
    mode: 'deep',
    kind: 'cli-contract',
    path: '/health',
  },
  {
    id: 'daiso.products',
    service: 'daiso',
    target: 'products',
    mode: 'quick',
    path: '/api/daiso/products?q=%ED%85%8C%EC%9D%B4%ED%94%84&pageSize=1',
    collectionKey: 'products',
    requiredFields: ['id', 'name', 'productName', 'itemName', 'goodsName'],
  },
  {
    id: 'cu.stores',
    service: 'cu',
    target: 'stores',
    mode: 'quick',
    path: '/api/cu/stores?keyword=%EA%B0%95%EB%82%A8&limit=1',
    collectionKey: 'stores',
    requiredFields: ['storeCode', 'storeName', 'name'],
  },
  {
    id: 'emart24.products',
    service: 'emart24',
    target: 'products',
    mode: 'quick',
    path: '/api/emart24/products?keyword=%EC%BB%A4%ED%94%BC&pageSize=1',
    collectionKey: 'products',
    requiredFields: ['pluCd', 'goodsName', 'itemName', 'name'],
    degradedFailurePatterns: EMART24_UPSTREAM_403_PATTERNS,
  },
  {
    id: 'gs25.products',
    service: 'gs25',
    target: 'products',
    mode: 'quick',
    path: '/api/gs25/products?keyword=%EC%BD%9C%EB%9D%BC&limit=1',
    collectionKey: 'products',
    requiredFields: ['itemCode', 'itemName', 'name'],
    degradedFailurePatterns: GS25_CLOUDFRONT_403_PATTERNS,
  },
  {
    id: 'gs25.stores',
    service: 'gs25',
    target: 'stores',
    mode: 'quick',
    path: '/api/gs25/stores?keyword=%EA%B0%95%EB%82%A8&limit=1',
    collectionKey: 'stores',
    requiredFields: ['storeCode', 'storeName', 'name'],
  },
  {
    id: 'seveneleven.products',
    service: 'seveneleven',
    target: 'products',
    mode: 'quick',
    path: '/api/seveneleven/products?query=%EC%BB%A4%ED%94%BC&size=1',
    collectionKey: 'products',
    requiredFields: ['itemCode', 'itemName', 'productNo', 'name'],
    degradedFailurePatterns: SEVENELEVEN_UPSTREAM_403_PATTERNS,
  },
  {
    id: 'lottemart.products',
    service: 'lottemart',
    target: 'products',
    mode: 'quick',
    path: '/api/lottemart/products?keyword=%EC%BD%9C%EB%9D%BC&storeCode=2301&area=%EC%84%9C%EC%9A%B8&pageLimit=1&source=zetta',
    collectionKey: 'products',
    requiredFields: ['productCode', 'name', 'productName'],
  },
  {
    id: 'oliveyoung.products',
    service: 'oliveyoung',
    target: 'products',
    mode: 'quick',
    path: '/api/oliveyoung/products?keyword=%EB%A6%BD%EB%B0%A4&size=1',
    collectionKey: 'products',
    requiredFields: ['goodsNumber', 'goodsName', 'productNo', 'productName', 'name'],
    timeoutMs: 5000,
  },
  {
    id: 'megabox.theaters',
    service: 'megabox',
    target: 'theaters',
    mode: 'quick',
    path: '/api/megabox/theaters?keyword=%EA%B0%95%EB%82%A8&limit=1',
    collectionKey: 'theaters',
    requiredFields: ['theaterCode', 'theaterName', 'name'],
  },
  {
    id: 'lottecinema.theaters',
    service: 'lottecinema',
    target: 'theaters',
    mode: 'quick',
    path: '/api/lottecinema/theaters?keyword=%EC%9E%A0%EC%8B%A4&limit=1',
    collectionKey: 'theaters',
    requiredFields: ['theaterCode', 'theaterName', 'name'],
  },
  {
    id: 'cgv.theaters',
    service: 'cgv',
    target: 'theaters',
    mode: 'quick',
    path: '/api/cgv/theaters?keyword=%EA%B0%95%EB%82%A8&limit=1',
    collectionKey: 'theaters',
    requiredFields: ['theaterCode', 'theaterName', 'name'],
  },
  {
    id: 'cu.inventory',
    service: 'cu',
    target: 'inventory',
    mode: 'deep',
    path: '/api/cu/inventory?keyword=%EC%BB%A4%ED%94%BC&size=1&storeLimit=0&storeCheck=false',
    collectionKey: 'inventoryItems',
    requiredFields: ['itemCode', 'itemName', 'name'],
  },
  {
    id: 'emart24.inventory',
    service: 'emart24',
    target: 'inventory',
    mode: 'deep',
    path: '/api/emart24/inventory?keyword=%EC%BB%A4%ED%94%BC&storeKeyword=%EA%B0%95%EB%82%A8&limit=1',
    collectionKey: 'inventoryItems',
    requiredFields: ['pluCd', 'goodsName', 'itemName', 'name'],
    degradedFailurePatterns: EMART24_UPSTREAM_403_PATTERNS,
  },
  {
    id: 'gs25.inventory',
    service: 'gs25',
    target: 'inventory',
    mode: 'deep',
    path: '/api/gs25/inventory?keyword=%EC%BD%9C%EB%9D%BC&storeKeyword=%EA%B0%95%EB%82%A8&limit=1',
    collectionKey: 'inventoryItems',
    requiredFields: ['itemCode', 'itemName', 'name'],
    degradedFailurePatterns: [
      '401 Unauthorized',
      '인증키가 제공되지 않음',
      ...GS25_CLOUDFRONT_403_PATTERNS,
    ],
  },
  {
    id: 'seveneleven.inventory',
    service: 'seveneleven',
    target: 'inventory',
    mode: 'deep',
    path: '/api/seveneleven/inventory?keyword=%EC%BB%A4%ED%94%BC&storeKeyword=%EA%B0%95%EB%82%A8&size=1',
    collectionKey: 'inventoryItems',
    requiredFields: ['itemCode', 'itemName', 'productNo', 'name'],
    degradedFailurePatterns: SEVENELEVEN_UPSTREAM_403_PATTERNS,
  },
  {
    id: 'oliveyoung.inventory',
    service: 'oliveyoung',
    target: 'inventory',
    mode: 'deep',
    path: '/api/oliveyoung/inventory?keyword=%EC%84%A0%ED%81%AC%EB%A6%BC&storeKeyword=%EB%AA%85%EB%8F%99&size=1&storeLimit=1&stockCheckLimit=0',
    collectionKey: 'inventoryProducts',
    requiredFields: ['goodsNumber', 'goodsName', 'productNo', 'productName', 'name'],
    timeoutMs: 5000,
  },
];
